const ImageName = {
	Tiles: 'tiles',
	PlayerWalk: 'player_walk',
	PlayerFall: 'player_fall',
	PlayerJump: 'player_jump',
	PlayerIdle: 'player_idle',
	PlayerRoll: 'player_roll',
	PlayerPray: 'player_pray',
	PlayerHeal: 'player_heal',
	PlayerAttack: 'player_attack',
	PlayerDeath: 'player_death',
	PlayerHurt: 'player_hurt',
	SkeletonIdle: 'skeleton_idle',
	SkeletonWalk: 'skeleton_walk',
	SkeletonAttack: 'skeleton_attack',
	SkeletonDeath: 'skeleton_death',
	SkeletonHurt: 'skeleton_hurt',
	SkeletonThrow: 'skeleton_throw',
	SkeletonThrownSword: 'Skeleton_thrown_sword',
	SkeletonShield: 'skeleton_shield',
	EyeAttack: 'eye_attack',
	EyeDeath: 'eye_death',
	EyeFlight: 'eye_flight',
	EyeProjectile: 'eye_projectile',
	EyeSpin: 'eye_spin',
	EyeHit: 'eye_hit',
};

export default ImageName;